/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    trucks: Truck;
    leads: Lead;
    'fleet-inquiries': FleetInquiry;
    media: Media;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    trucks: TrucksSelect<false> | TrucksSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'fleet-inquiries': FleetInquiriesSelect<false> | FleetInquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trucks".
 */
export interface Truck {
  id: number;
  title?: string | null;
  year: number;
  make:
    | 'isuzu'
    | 'hino'
    | 'freightliner'
    | 'nissan'
    | 'volvo'
    | 'peterbilt'
    | 'kenworth'
    | 'mack'
    | 'international'
    | 'other';
  model: string;
  /**
   * e.g. "16FT Box"
   */
  trim?: string | null;
  bodyType: 'box-truck' | 'reefer' | 'landscaper' | '26ft-box-truck' | 'dump-truck' | 'tow-truck';
  /**
   * Optional. Custom headline for this listing (shown on the card and detail page). Leave blank to use "{year} {make} {model} {trim}".
   */
  listingTitle?: string | null;
  /**
   * Optional. If provided, must be 17 characters — validated on save.
   */
  vin?: string | null;
  /**
   * Whole US dollars
   */
  price: number;
  /**
   * Internal only — not shown on the site.
   */
  condition?: ('excellent' | 'good' | 'fair') | null;
  /**
   * Shown on the listing to build buyer trust.
   */
  titleStatus?: ('clean' | 'rebuilt' | 'salvage' | 'lien') | null;
  /**
   * Number of previous owners. Leave blank if unknown.
   */
  owners?: number | null;
  mileage: number;
  fuelType: 'diesel' | 'gasoline';
  /**
   * Gross vehicle weight rating (lb)
   */
  gvwr?: number | null;
  payloadClass?: ('class-3' | 'class-4' | 'class-5' | 'class-6' | 'class-7' | 'class-8') | null;
  /**
   * e.g. "5.2L Diesel I4"
   */
  engine?: string | null;
  /**
   * e.g. "Auto · 6-spd"
   */
  transmission?: string | null;
  drivetrain?: ('RWD' | '4WD' | 'AWD') | null;
  /**
   * Shown as an inspection block on the listing. Only filled-in items appear — leave blank what you did not check.
   */
  inspection?: {
    /**
     * When it was inspected
     */
    inspectedDate?: string | null;
    /**
     * Technician or shop name
     */
    inspectedBy?: string | null;
    /**
     * Overall condition summary (optional).
     */
    summary?: string | null;
    /**
     * One row per system you checked. The rating sets the color shown on the listing.
     */
    points?:
      | {
          area:
            | 'engine'
            | 'transmission'
            | 'brakes'
            | 'tires'
            | 'suspension'
            | 'electrical'
            | 'frame'
            | 'emissions'
            | 'interior'
            | 'body';
          rating: 'good' | 'fair' | 'attention';
          /**
           * Optional detail
           */
          note?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Upload or select multiple photos at once (drag several files straight in). Drag to reorder — the first photo is the main one. At least one required to publish.
   */
  photos?: (number | Media)[] | null;
  /**
   * Paste a YouTube or Vimeo link. Preferred: it plays fast on phones and uses no site storage. If this is filled in it is used instead of an uploaded file.
   */
  videoUrl?: string | null;
  /**
   * MP4 or WebM, 64MB max. Use only when a link is not practical — uploaded video is served exactly as-is, so keep clips short and compress before uploading.
   */
  videoFile?: (number | null) | Media;
  /**
   * Optional PDF spec sheet
   */
  specSheet?: (number | null) | Media;
  /**
   * Customer-facing narrative. Short sentences, specs before adjectives.
   */
  description: string;
  /**
   * Whether this listing is live on the website. To mark a truck sold, use Availability below — not this field.
   */
  status: 'draft' | 'pending-review' | 'published' | 'archived';
  /**
   * Sold trucks drop out of inventory browsing, but their page stays live and marked SOLD so old links and Google results still work. Sale Pending stays listed and keeps taking inquiries.
   */
  availability: 'available' | 'pending' | 'sold';
  /**
   * Featured trucks show in the home Featured Inventory section, sort first in the inventory (default order), and get a “Featured” badge on their card.
   */
  featured?: boolean | null;
  /**
   * Note to the employee when sending a draft back. Not shown publicly.
   */
  reviewNote?: string | null;
  stockNumber?: string | null;
  slug?: string | null;
  assignedEmployee?: (number | null) | User;
  publishedAt?: string | null;
  soldAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo for accessibility and SEO (e.g. "2019 Isuzu NPR-HD front 3/4 view").
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Admins can publish trucks and manage everything. Employees create drafts.
   */
  role: 'admin' | 'employee';
  /**
   * Optional. Internal contact only.
   */
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  fullName?: string | null;
  phone?: string | null;
  email?: string | null;
  message?: string | null;
  source: 'truck-inquiry' | 'financing-prequal' | 'general-contact';
  /**
   * Auto-populated for truck inquiries.
   */
  truckOfInterest?: (number | null) | Truck;
  financingInterest?: boolean | null;
  tradeIn?: boolean | null;
  tradeInYearMakeModel?: string | null;
  tradeInMileage?: number | null;
  tradeInCondition?: string | null;
  heardAboutUs?: ('google' | 'facebook' | 'referral' | 'drove-by-lot' | 'other') | null;
  website?: string | null;
  status: 'new' | 'contacted' | 'closed-sold' | 'closed-lost';
  internalNotes?: string | null;
  receivedAt?: string | null;
  contactedAt?: string | null;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-inquiries".
 */
export interface FleetInquiry {
  id: number;
  companyName: string;
  contactName: string;
  phone: string;
  email: string;
  fleetSize: '1-3' | '4-10' | '10-plus';
  timeline: 'asap' | '1-3-months' | '3-6-months' | 'ongoing';
  trucksNeeded: string;
  heardAboutUs?: ('google' | 'facebook' | 'referral' | 'drove-by-lot' | 'other') | null;
  website?: string | null;
  status: 'new' | 'sourcing' | 'presented' | 'closed-sold' | 'closed-lost';
  internalNotes?: string | null;
  receivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: 'home' | 'about' | 'financing' | 'parts' | 'contact';
  title: string;
  /**
   * For SEO. ~150-160 characters.
   */
  metaDescription?: string | null;
  /**
   * Small label above the title, e.g. "ABOUT SPARTA MOTORS".
   */
  heroLabel?: string | null;
  /**
   * Big display title. Line breaks are respected.
   */
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  sections?:
    | (
        | {
            label?: string | null;
            title?: string | null;
            lead?: string | null;
            steps?:
              | {
                  num?: string | null;
                  title: string;
                  desc?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            label?: string | null;
            title?: string | null;
            lead?: string | null;
            items?:
              | {
                  name: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'infoListBlock';
          }
        | {
            label?: string | null;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            formType: 'financing-prequal' | 'general-contact';
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formBlock';
          }
        | {
            size?: ('small' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapBlock';
          }
        | {
            label?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBlock';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'trucks';
        value: number | Truck;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'fleet-inquiries';
        value: number | FleetInquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trucks_select".
 */
export interface TrucksSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  make?: T;
  model?: T;
  trim?: T;
  bodyType?: T;
  listingTitle?: T;
  vin?: T;
  price?: T;
  condition?: T;
  titleStatus?: T;
  owners?: T;
  mileage?: T;
  fuelType?: T;
  gvwr?: T;
  payloadClass?: T;
  engine?: T;
  transmission?: T;
  drivetrain?: T;
  inspection?:
    | T
    | {
        inspectedDate?: T;
        inspectedBy?: T;
        summary?: T;
        points?:
          | T
          | {
              area?: T;
              rating?: T;
              note?: T;
              id?: T;
            };
      };
  photos?: T;
  videoUrl?: T;
  videoFile?: T;
  specSheet?: T;
  description?: T;
  status?: T;
  availability?: T;
  featured?: T;
  reviewNote?: T;
  stockNumber?: T;
  slug?: T;
  assignedEmployee?: T;
  publishedAt?: T;
  soldAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  message?: T;
  source?: T;
  truckOfInterest?: T;
  financingInterest?: T;
  tradeIn?: T;
  tradeInYearMakeModel?: T;
  tradeInMileage?: T;
  tradeInCondition?: T;
  heardAboutUs?: T;
  website?: T;
  status?: T;
  internalNotes?: T;
  receivedAt?: T;
  contactedAt?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-inquiries_select".
 */
export interface FleetInquiriesSelect<T extends boolean = true> {
  companyName?: T;
  contactName?: T;
  phone?: T;
  email?: T;
  fleetSize?: T;
  timeline?: T;
  trucksNeeded?: T;
  heardAboutUs?: T;
  website?: T;
  status?: T;
  internalNotes?: T;
  receivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  metaDescription?: T;
  heroLabel?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  sections?:
    | T
    | {
        stepsBlock?:
          | T
          | {
              label?: T;
              title?: T;
              lead?: T;
              steps?:
                | T
                | {
                    num?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        infoListBlock?:
          | T
          | {
              label?: T;
              title?: T;
              lead?: T;
              items?:
                | T
                | {
                    name?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calloutBlock?:
          | T
          | {
              label?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              formType?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        mapBlock?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
        statsBlock?:
          | T
          | {
              label?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  hoursMonFri?: string | null;
  hoursSat?: string | null;
  hoursSun?: string | null;
  socialFacebook?: string | null;
  socialInstagram?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
        latitude?: T;
        longitude?: T;
      };
  hoursMonFri?: T;
  hoursSat?: T;
  hoursSun?: T;
  socialFacebook?: T;
  socialInstagram?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}